# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_profilefeedimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeedimage',
            old_name='created_by',
            new_name='user_profile',
        ),
    ]
