# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20170907_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefeedimage',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
    ]
