# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auto_20170907_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefeeditem',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profilefeedimage',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
