# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_auto_20170907_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='image',
            new_name='user_profile_image',
        ),
    ]
